services:
  lab-web:
    image: nginx:alpine
    container_name: lab-web
    restart: unless-stopped
    volumes:
      - ./web:/usr/share/nginx/html:ro
    networks:
      - home_lab

networks:
  home_lab:
